services:
  - type: web
    name: connectify-backend
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://NehaReddy:neha1234@cluster-connectify.q3scigs.mongodb.net/connectify?retryWrites=true&w=majority"
      - key: JWT_KEY
        value: "I3AXLXwue87xy52iTDG7fQCRRwPS0Ryd"
